---
- name: Установка etcd
  apt:
    name: etcd-client
    name: etcd-server
    state: present
    update_cache: yes

- name: Создание директории etcd 
  file:
    path: "{{ etcd_data_dir }}"
    state: directory
    owner: etcd
    group: etcd
    mode: '0750'

- name: Конфигурация etcd
  template:
    src: etcd.conf.j2
    dest: /etc/default/etcd
    owner: root
    group: root
    mode: '0640'

- name: Включение и запуск etcd
  systemd:
    name: etcd
    state: started
    enabled: yes
    daemon_reload: yes

- name: Ожидание формирования etcd кластера
  wait_for:
    port: "{{ etcd_listen_client_port }}"
  delay: 5
  timeout: 60

- name: Проверка etcd кластера
  command: etcdctl --endpoints=http://localhost:2379 endpoint health
  environment:
    ETCDCTL_API: "3"
  register: etcd_health
  changed_when: false
  failed_when: "'healthy' not in etcd_health.stderr"
  debug:
    msg: "{{ etcd_health.stderr }}"

- name: Перезапуск etcd
  systemd:
    name: etcd
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Проверка etcd на нодах
  command: etcdctl --endpoints=http://10.10.10.1:2379,http://10.10.10.2:2379,http://10.10.10.3:2379 endpoint health
  environment:
    ETCDCTL_API: "3"
  register: etcd_health
  changed_when: false
  failed_when: "'healthy' not in etcd_health.stderr"
