---
    - name: Stop Patroni service
      systemd:
        name: patroni
        state: stopped

    - name: Clear existing cluster state in etcd
      command: >
        etcdctl del /service/postgres --prefix
      environment:
        ETCDCTL_API: "3"
      when: inventory_hostname == groups['patroni_cluster'][0]

    - name: Initialize PostgreSQL data directory
      become_user: postgres
      become: yes
      command: sudo -u postgres /usr/lib/postgresql/15/bin/initdb -D /var/lib/postgresql/15/main
        --encoding=UTF8
        --data-checksums
      args:
        creates: "{{ postgres_data_dir }}/PG_VERSION"
      when: inventory_hostname == groups['patroni_cluster'][0]

    - name: Start Patroni service
      systemd:
        name: patroni
        state: started

    - name: Ensure PostgreSQL is stopped (if started manually)
      become_user: postgres
      command: "{{ postgres_bin_dir }}/pg_ctl -D {{ postgres_data_dir }} stop"
      ignore_errors: yes
      when: inventory_hostname == groups['patroni_cluster'][0]

    - name: Start Patroni service
      systemd:
        name: patroni
        state: started

    - name: Wait for cluster initialization
      command: "patronictl -c /etc/patroni.yml list"
      register: cluster_status
      until: "'Leader' in cluster_status.stdout"
      retries: 10
      delay: 10
      changed_when: false
