---
    - name: Check for system ID mismatch errors
      command: >
        systemctl status patroni |
        grep "system ID mismatch" || echo "NO_ERROR"
      register: patroni_error_check
      changed_when: true
      ignore_errors: yes

    - name: Set fact when error detected
      set_fact:
        needs_recovery: true
      when: '"system ID mismatch" in patroni_error_check.stdout'

    - name: Наличие ошибок
      debug:
        msg: "System ID mismatch detected"
      when: needs_recovery|default(false)

    - name: Stop Patroni service on affected nodes
      systemd:
        name: "patroni"
        state: stopped
      when: needs_recovery|default(false)

    - name: Remove PostgreSQL data directory contents
      become: yes
      command: rm -rf /var/lib/postgresql/15/main/*
      when: needs_recovery|default(false)

    - name: Start Patroni service
      systemd:
        name: "patroni"
        state: started
      when: needs_recovery|default(false)

    - name: Set PostgreSQL data directory permissions
      become: yes
      file:
        path: /var/lib/postgresql/15/main/*
        mode: '0750'
        owner: postgres
        group: postgres
        state: directory

    - name: Display recovery status
      debug:
        msg: "Recovery completed"
      when: needs_recovery|default(false)
